_format_version: '2.1'

services:
    - connect_timeout: 60000
      host: mockbin.org
      name: example_service
      port: 80
      protocol: http
      read_timeout: 60000
      retries: 5
      write_timeout: 60000
      routes:
          - name: mocking
            paths:
                - /
            path_handling: v0
            preserve_host: false
            protocols:
                - http
                - https
            regex_priority: 0
            strip_path: true

plugins:
    - name: perimeterx
      config:
          px_appId: PXvRfnOj4y
          auth_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZXMiOlsicmlza19zY29yZSIsInJlc3RfYXBpIl0sImlhdCI6MTU5NDg5OTEzNiwic3ViIjoiUFh2UmZuT2o0eSIsImp0aSI6IjNmNDkyNzA2LTQ2ZjItNDBlMy05ZjgxLTg4MzdmNjFkYWU3YSJ9.FCs49WM_-6mBS5SXZvKuNsnsgqcCq9C8pQLg2YgXyeQ
          cookie_secret: Aoyza2bmkUl3437FbJtHarY3Dn3ufhoj0W689QHx1urTJhaN0jI5Fw6yf8Mma322
          px_debug: true
          ip_headers:
              - X-Forwarded-For
          blocking_score: 100
          first_party_enabled: true
          block_enabled: true
