_format_version: '2.1'

services:
    - connect_timeout: 60000
      host: mockbin.org
      name: example_service
      port: 80
      protocol: http
      read_timeout: 60000
      retries: 5
      write_timeout: 60000
      routes:
          - name: mocking
            paths:
                - /
            path_handling: v0
            preserve_host: false
            protocols:
                - http
                - https
            regex_priority: 0
            strip_path: true

plugins:
    - name: perimeterx
      config:
          px_appId: <REPLACE>
          auth_token: <REPLACE>
          cookie_secret: <REPLACE>
          px_debug: true
          ip_headers:
              - X-Forwarded-For
          blocking_score: 100
          first_party_enabled: true
          block_enabled: true
